### ISSUE TITLE
When using config file, exiting guard doesn't kill puma

### ISSUE THREAD

**Issue by dsandstrom** [jc00ke/guard-puma#18]
I tried to use a custom puma config file instead of using Guardfile options.  However, I noticed stopping/exiting guard doesn't kill puma.  I have to find and kill the pid.  Is there something I need to add to the config file to make them compatible?

**Comment by jc00ke** [comment]
Hmm, can you set up a reproduction and I'll try to poke around at it.

**Comment by jc00ke** [comment]
@dsandstrom mind giving that branch a try?

**Comment by dsandstrom** [comment]
That's working.  Thanks for fixing it.

**Comment by jc00ke** [comment]
Cool, I'll cut a new release.
