### ISSUE TITLE
Environment option broken

### ISSUE THREAD

**Issue by ealders** [jc00ke/guard-puma#21]
Looks like when you guys made changes for the v0.3.2 you broke the environment option passed in from the guardfile. Basically, it ignores the option passed in and runs under the default development environment.

**Comment by jc00ke** [comment]
Oof, sorry about that. TBH I don't use this anymore, so I don't catch these kinds of bugs. Do you have any interest in fixing it, or adding a spec that display the bug? I won't have time to look into it until the weekend.

**Comment by jc00ke** [comment]
@ealders can you give 374dceb a whirl and let me know if it fixes it?

**Comment by ealders** [comment]
@jc00ke - Just pulled the latest commit and looks good.

**Comment by jc00ke** [comment]
Fixed by 374dceb
